# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bgardner/workspace/wasm_softcore/wasm_softcore.srcs/sources_1/bd/System/ip/System_blk_mem_gen_0_0/System_blk_mem_gen_0_0.xci
# IP: The module: 'System_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bgardner/workspace/wasm_softcore/wasm_softcore.srcs/sources_1/bd/System/ip/System_blk_mem_gen_0_0/System_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/bgardner/workspace/wasm_softcore/wasm_softcore.srcs/sources_1/bd/System/ip/System_blk_mem_gen_0_0/System_blk_mem_gen_0_0.xci
# IP: The module: 'System_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bgardner/workspace/wasm_softcore/wasm_softcore.srcs/sources_1/bd/System/ip/System_blk_mem_gen_0_0/System_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'System_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
